#ifndef _UPDATECONTROLS_H_
#define _UPDATECONTROLS_H_

void UPDATECONTROLS_CZ();
void UPDATECONTROLS_CZALT();
void UPDATECONTROLS_FM();
void UPDATECONTROLS_FMALT();
void UPDATECONTROLS_DRUM();

#endif